version: '3'

services:
  nginx:
    container_name: 42nginx
    build:
      context: ./requirements/nginx
    image: 42_nginx
    volumes:
      - wordpress-volume:/var/www/html
    ports:
      - "443:443"
    networks:
      - front
    restart: unless-stopped

  mariadb:
    container_name: 42mariadb
    build:
      context: ./requirements/mariadb
    image: 42_mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - back
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: unless-stopped

  wordpress:
    container_name: 42wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: 42_wordpress
    volumes:
      - wordpress-volume:/var/www/html
    ports:
      - 9000:9000
    networks:
      - front
      - back
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_USER_MAIL=${WP_USER_MAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_PREFIX=${WP_PREFIX}
      - WP_TITLE=${WP_TITLE}
    restart: unless-stopped

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/cmorel-a/data/database
      type: none
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/cmorel-a/data/wordpress
      type: none
      o: bind

networks:
  front:
  back:
